analytics-id: 
#Pages
pages:
  - {name: 'Episoden', link: 'episodes.html'}
  - {name: 'Über', link: '#'}

social:
#  - {icon: 'instagram', type: "brand", link: '#'}
  - {icon: 'twitter', type: "brand", link: 'https://twitter.com/NeulichInternet'}
#  - {icon: 'facebook', type: "brand", link: '#'}
  - {icon: 'youtube', type: "brand", link: 'https://www.youtube.com/channel/UCYUofAXgSMmKaG_njeEUUhw'}  
#  - {icon: 'envelope', type: "solid", link: 'mailto:alessiofranceschi2@gmail.com'}
  - {icon: 'rss', type: "solid", link: "https://anchor.fm/s/55cf0ecc/podcast/rss"}

websites-podcast:
#  - {name: 'Apple Podcast', link: '#'}
  - {name: 'Spotify', link: 'https://open.spotify.com/show/2CduZE7eQiR3oXZho9BjZm'}
  - {name: 'YouTube', link: 'https://www.youtube.com/channel/UCYUofAXgSMmKaG_njeEUUhw'}
  - {name: 'Pocket Casts', link: 'https://pca.st/58v32ol1'}
  - {name: 'Amazon Music', link: 'https://music.amazon.de/podcasts/94f56ca6-dfd9-4758-9286-0910de7b4865/Neulich-im-Netz-Der-InternetPodcast'}
  - {name: 'Google Podcast', link: 'https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy81NWNmMGVjYy9wb2RjYXN0L3Jzcw=='}
  - {name: 'Anchor', link: 'https://anchor.fm/neulich-im-netz'}
  - {name: 'Apple Podcast', link: 'https://podcasts.apple.com/us/podcast/neulich-im-netz-der-internet-podcast/id1577825207'}
#  - {name: 'Overcast', link: '#'}
  - {name: 'RadioPublic', link: 'https://radiopublic.com/neulich-im-netz-der-internetpodc-Gmj9aa'}
  - {name: 'Breaker', link: 'https://www.breaker.audio/neulich-im-netz-der-internet-podcast'}  
  - {name: 'RSS', link: 'https://anchor.fm/s/55cf0ecc/podcast/rss'}

translate-date: true #See _includes/date.html to translate the months' name
shownotes: false

#Disqus
disqus:
  disqus_shortname: 
